### PR TITLE
Fix Logout Issue

### LINKED ISSUE #3: Error in Logout because of missing property in Auth0Client service registration
Logout throws an error because in the example there is a `PostLogoutRedirectUri` property missing!
How it should be:
```csharp
builder.Services.AddSingleton(new Auth0Client(new()
{
    Domain = "<domain>",
    ClientId = "<client id>",
    Scope = "openid profile",
    RedirectUri = "myapp://callback",
    PostLogoutRedirectUri = "myapp://callback",
}));
```
How it is:
```csharp
builder.Services.AddSingleton(new Auth0Client(new()
{
    Domain = "<domain>",
    ClientId = "<client id>",
    Scope = "openid profile",
    RedirectUri = "myapp://callback"
}));
```

### PR DESCRIPTION
**Pull request by Jon-Corey**
Fixes #3 

This fixes the error described in the issue report above by adding the `PostLogoutRedirectUri` property to the Auth0Client.

The "Configure authentication in your MAUI app" section of the article associated with this repo will need to be updated to reflect this change. [Article](https://auth0.com/blog/add-authentication-to-blazor-hybrid-apps-in-dotnet-maui/#:~:text=Configure%20authentication%20in%20your%20MAUI%20app).

### CODE REVIEW

File: MauiProgram.cs [hunk 1]
```diff
@@ -28,7 +28,8 @@ public static MauiApp CreateMauiApp()
             Domain = "<YOUR_AUTH0_DOMAIN>",
             ClientId = "<YOUR_CLIENT_ID>",
             Scope = "openid profile",
-            RedirectUri = "myapp://callback/"
+            RedirectUri = "myapp://callback/",
+            PostLogoutRedirectUri = "myapp://callback"
```
Comment (andychiare) [inline MauiProgram.cs]: For consistency with the updated article, it should be as follows:

```suggestion
            PostLogoutRedirectUri = "myapp://callback/"

```

**Review by andychiare — DISMISSED** [review]

**Review by jtemporal — APPROVED** [review]
LGTM

**Review by jtemporal — APPROVED** [review]
